# Generated by Django 5.1.7 on 2025-03-13 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.IntegerField()),
                ('user_id', models.IntegerField()),
                ('user_name', models.CharField(max_length=200)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('book_title', models.CharField(max_length=150)),
                ('book_price', models.FloatField()),
                ('book_quantity', models.IntegerField()),
                ('state', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('district', models.CharField(max_length=200)),
                ('street', models.CharField(max_length=200)),
                ('house_number', models.IntegerField()),
                ('cep', models.IntegerField()),
                ('payment_method', models.CharField(max_length=200)),
                ('card_name', models.CharField(max_length=200)),
                ('card_number', models.IntegerField()),
                ('card_security_code', models.IntegerField()),
                ('card_validity_month', models.IntegerField()),
                ('card_validity_year', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
