# Generated by Django 5.1.7 on 2025-03-13 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_price',
            field=models.IntegerField(default=0.0),
            preserve_default=False,
        ),
    ]
